[package]
name = "markle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
murmur3 = "0.5.2"
uuid = { version = "0.8", features = ["v4"] }

